### ISSUE TITLE
config variables

### ISSUE THREAD

**Issue by wjlei1990** [chukren/pyadjoint#10]
In pyadjoint.Config:

```
                 transfunc_waterlevel=1.0E-10,
                 water_threshold=0.02,
```

These are two different variables, right? The later one seems to be added recently?

**Comment by chukren** [comment]
"transfunc_waterlevel" is for multi-taper transfer functions and the value is hard-code which shall be updated but have not found a proper way to do it.
"water_threshold" is used from search frequency limits in a spectra in percentage.
