### ISSUE TITLE
config should be seperated for different type of measurements

### ISSUE THREAD

**Issue by wjlei1990** [chukren/pyadjoint#11]
Hi,

The `Config` should be separated for different types of measurements. Now, in pypaw, I implemented a very strict parameter list check to make sure that users provide all the arguments in the `Config.__init__`. This will cause issues when people only want to use `cc_traveltime` or `waveform_misfit` since they need to provide the whole config arg list.

**Comment by chukren** [comment]
Done in the latest commit (Oct 26-27, 2016).
