### ISSUE TITLE
dt_sigma_min missing from config list

### ISSUE THREAD

**Issue by wjlei1990** [chukren/pyadjoint#5]
This variable is used in `cc_traveltime.config`, but not listed in `Config` object.

**Comment by wjlei1990** [comment]
Config object could be better organised.

Defining unnecessary variables to accommodate different measurements is a bad idea, will cause potential bugs in the future. 

Solutions:
1) define a parent(or super) class `ConfigBase` and child class for different measurements.
2) directly define different `Config` classes for different measurements.

**Comment by chukren** [comment]
Thanks, I agree.  This is the latest updates which not reflected in pytomo3d yet.  I think I will go with a different Config class for each type of measurement so the future users can have more flexibility to add their own type of adjoint sources

**Comment by chukren** [comment]
dev branch has been merged to master and will be removed. All to do list will be transferred to master branch.
