### ISSUE TITLE
new add argument is not compatable with old version

### ISSUE THREAD

**Issue by wjlei1990** [chukren/pyadjoint#7]
Hi,

A new argument is added to `AdjointSource`, which should be made as a keyword instead.

Here:

```
    def __init__(self, adj_src_type, misfit, measurement, dt, min_period,
                 max_period, component, adjoint_source=None, network=None,
                 station=None, location=None, starttime=None):
```

Should be defined as:

```
    def __init__(self, adj_src_type, misfit, dt, min_period,
                 measurements=None, max_period, component, adjoint_source=None, network=None,
                 station=None, location=None, starttime=None):
```

Otherwise all the old code will crash...

By defination, this should not be made as a argument, but a keyword(which makes it optional).

**Comment by wjlei1990** [comment]
Please also make changes to other places if necessary.

**Comment by chukren** [comment]
Done,  "measurement" changed from argument to keyword.
